apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "<your_gmail_id>" #enter your email to get the id
  GMAIL_PASSWORD: "<gmail_generated_password>"
type: Opaque